### PR TITLE
Fixes the call to setsockopt(SO_UPDATE_ACCEPT_CONTEXT) on Windows (#1598)

### LINKED ISSUE #1598: http_server deadlocks on shutdown
**Describe the bug**
Probably is not a bug, but an issue on my code, but I cannot figure out what should be done.

So, before calling it a bug, I would like to know if the shutdown code is correct, or I missed some other function.

**Expected behavior**
After receiving a particular GET query, the server must shut down.

**Actual Behavior**
The server deadlocks in `nng_http_server_stop`

** Environment Details **
 - latest master (41ce9fbfd7a396816dab08dcb0284bab4329c622)
 - Windows 10
 - C++
 - Static library

**Additional context**
The issue is a lot more visible when using the VPN client `AstrillVPN`. 
With it, it happens like 80% of the times, even if it is not enabled (just being installed).

**To Reproduce**

The following code deadlocks. 
All error handling has been removed for clarity. No errors are thrown.

The code deadlocks when calling `nng_http_server_stop()`.
It hangs waiting for closing of all connections (in `http_server_stop()`, line `nni_cv_wait(&s->cv);` )

While the reaper thread trying to close the connections is waiting for completion of the task on `conn->rd_aio`
(in `nni_http_conn_fini()`, line `nni_aio_stop(conn->rd_aio);`

Thank you for any input you can provide, as I am out of ideas about what to do here....
Best regards,
Ruben

```
#include <nng/nng.h>
#include <nng/supplemental/http/http.h>

#include <iostream>
#include <string>
#include <thread>
#include <chrono>
#include <atomic>

std::atomic<bool> callback_done(false);

static void handler_callback(nng_aio *io) {
    // Actual handler work and response generation
    callback_done = true;
    
    nng_http_res *nng_res=NULL;
    nng_http_res_alloc(&nng_res);
    
    // It doesn't matter if it is just a redirection or an actual HTML page.
    
    //nng_http_res_set_status(nng_res, 302);
    //nng_http_res_set_header(nng_res, "Location", "https://www.google.com");
    //nng_http_res_set_header(nng_res, "Connection", "close");
    
    nng_http_res_set_status(nng_res, 200);
    std::string body = "<html><body>Hello World</body></html>";
    nng_http_res_copy_data(nng_res, body.c_str(), body.size());
    
        
    // Return the response
    nng_aio_set_output(io, 0, nng_res);
    
    // And finish aio
    nng_aio_finish(io, 0);
}

int main (int argc, char *argv[]) {
    // Setup server
    // ------------
    
    // Create server
    nng_http_server *server = nullptr;
    {
        nng_url *server_url=nullptr;
        nng_url_parse(&server_url, "http://127.0.0.1:8080");
    
        nng_http_server_hold( &server, server_url);
        nng_url_free(server_url);
    }
    
    // Create and add handler
    nng_http_handler *nng_handler=nullptr;
    nng_http_handler_alloc(&nng_handler, "/callback", &handler_callback);
    nng_http_server_add_handler(server, nng_handler);
        
    // Start server   
    nng_http_server_start(server);
    
    // Normal Server Work
    // ------------------
    
    // Wait for the callback to be called
    while (!callback_done) {
        std::this_thread::sleep_for(std::chrono::milliseconds(20));
    }
    
    // Shutdown server
    // ---------------
    
    // Stop server
    nng_http_server_stop(server); // HERE it deadlocks waiting for completion of the task on conn->rd_aio
    
    // Remove handler
    nng_http_server_del_handler(server, nng_handler);
    
    // Destroy server and handler
    nng_http_server_release(server);
    nng_http_handler_free(nng_handler);
    
    return 0;
}

```

### PR DESCRIPTION
**Pull request by L0PiTaL**
From the [docs](https://docs.microsoft.com/en-us/windows/win32/api/mswsock/nf-mswsock-acceptex), this function requires as a parameter the listener socket, not a boolean value.
With this change, `shutdown` now can start the socket closing process correctly.

fixes #1598

### CODE REVIEW

File: src/platform/windows/win_tcpconn.c [hunk 1]
```diff
@@ -260,7 +260,13 @@ tcp_close(void *arg)
 	if (!c->closed) {
 		c->closed = true;
 		if (!nni_list_empty(&c->recv_aios)) {
-			CancelIoEx((HANDLE) c->s, &c->recv_io.olpd);
```
Comment (gdamore) [inline src/platform/windows/win_tcpconn.c:263]: So the problem is that closing the socket didn't up the waiting receivers?  Is that the situation?  (A similar problem exists with UNIX and there some unfortunate workarounds for it in the POSIX side of the code.)

Comment (L0PiTaL) [reply src/platform/windows/win_tcpconn.c]: @gdamore 

FINALLY!
After your comment about closing the socket, I have checked the result of `shutdown()` and it also was raising an error (`WSAENOTCONN`).

After searching this error, it came from an issue on the call to `setsockopt(SOL_SOCKET, SO_UPDATE_ACCEPT_CONTEXT)` after AcceptEx.

From the [docs](https://docs.microsoft.com/en-us/windows/win32/api/mswsock/nf-mswsock-acceptex), this function requires as a parameter the listener socket, not a boolean value.

Now it closes the connections correctly.

I have rebsaed this PR with these new changes, so it should be ready for review.

Comment (gdamore) [reply src/platform/windows/win_tcpconn.c]: Excellent.  Strange behavior in Windows around this, but clearly what I had was a bug.
